apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: auth
spec:
  replicas: 1
  serviceName: "auth"
  selector:
    matchLabels:
      app: auth
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: auth
    spec:
      initContainers:
        - name: migrations-container
          image: MIGRATIONS_IMAGE
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: db-secrets
      containers:
        - name: auth-container
          image: AUTH_IMAGE
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: db-secrets
          resources:
            requests:
              memory: "300Mi"
              cpu: "500m"
            limits:
              memory: "600Mi"
              cpu: "1000m"