apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: auth
  labels:
    app: auth
spec:
  replicas: 1
  serviceName: "auth"
  selector:
    matchLabels:
      app: auth
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: auth
    spec:
      initContainers:
        - name: migrations-container
          image: dm874/auth-migrations:5e8b9735bdbc4c13c4337b494bcb7de0f7d5b8b5
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: db-secrets
      containers:
        - name: auth-container
          image: dm874/auth:5e8b9735bdbc4c13c4337b494bcb7de0f7d5b8b5
          imagePullPolicy: Always
          ports:
            - containerPort: 8084
              name: auth-port
          envFrom:
            - secretRef:
                name: db-secrets
            - secretRef:
                name: jwt-secret
          resources:
            requests:
              memory: "300Mi"
              cpu: "500m"
            limits:
              memory: "600Mi"
              cpu: "1000m"
